### ISSUE TITLE
Create an importable `version` `cobra.Command`

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/release-utils#23]
I feel like we write a `version` package/version for multiple projects. Could we abstract/de-dupe?

Consider writing this as a package in sigs.k8s.io/release-utils that can be an importable `cobra.Command`.

See https://github.com/kubernetes/enhancements/tree/master/pkg/kepctl/commands for an example, as well @n3wscott's comments in https://github.com/kubernetes/enhancements/pull/2387#pullrequestreview-579854747 for more background.

_Originally posted by @justaugustus in https://github.com/kubernetes-sigs/bom/pull/27#pullrequestreview-860236487_

**Comment by n3wscott** [comment]
I like it. Take a look at what we did in cosign: https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/version.go

The cli calls to the version package lib and spits out a bunch of standard things. https://github.com/sigstore/cosign/blob/main/pkg/version/version.go

**Comment by justaugustus** [comment]
Thanks Scott!!!

**Comment by cpanato** [comment]
thanks scott 🎉

**Comment by n3wscott** [comment]
doom font http://www.figlet.org/fonts/doom.flf
