### ISSUE TITLE
Investigate moving some of these utilities into k8s.io/utils

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/release-utils#7]
ref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1615238311084800
cc: @thockin @kubernetes-sigs/release-engineering

**Comment by justaugustus** [comment]
cc: @dims

**Comment by thockin** [comment]
Regarding deps.  k8s.io/utils is supposed to be a) very general-purpose and b) a leaf repository.

(A) means, in practice:
- no kubernetes concepts
- no kubernetes nouns
- extra attention to API and docs

(B) means, in practice:
- no deps on ANYTHING k8s.io except other libs in the same repo
- no deps on other ecosystem libs unless it's aggressively obviously safe

As I peeked at this repo I see logrus as an example of violating (B).  Other than the logs dir it doesn't seem to be very important.

**Comment by justaugustus** [comment]
Sounds great! Thanks for the feedback, Tim!

**Comment by saschagrunert** [comment]
Yes I agree we should keep the release-utils coupled to k/release{-sdk}. Beside that, we can decide case by case if it's worth to make single packages within this repository more generic.
