### ISSUE TITLE
GenerateLDFlags function doesn't work on OSX

### ISSUE THREAD

**Issue by rappizs** [kubernetes-sigs/release-utils#90]
The `getBuildDateTime` helper function, which is called by `mage.GenerateLDFlags`, doesn't work under OSX. The `date` command is a little bit different on OSX than on Linux and doesn't support the `-d` flag, therefore on OSX we get this error when trying to use `mage.GenerateLDFlags`: `date: illegal option -- d`

The exact problem is here: https://github.com/kubernetes-sigs/release-utils/blob/1bf6b4c5d954414cf0485ec5006d7bd020c956f3/mage/version.go#L62

**Comment by saschagrunert** [comment]
Hm, we can probably generate the date from native golang libraries other than relying on GNU date.

**Comment by rappizs** [comment]
Already created a fix for it using GNU date: https://github.com/rappizs/release-utils/commit/e92530446975addaad9e949ad1d584a91083979e, but I agree that maybe some native go solution would be better.

**Comment by saschagrunert** [comment]
Yeah, like this: https://github.com/kubernetes-sigs/release-utils/pull/91

**Comment by justaugustus** [comment]
Thanks @saschagrunert!
